More specific nomenclature in TransportCrossSections.
chi-tech/chi-tech pull request #134
Opened 2021-05-21 18:04 UTC by zachhardy

Changed the nomenclature in the TransportCrossSections class to be more informative.

G -> num_groups
L -> scattering_order
J -> num_precursors

This addresses issue #133.

2021-05-21 20:03 UTC, ragusa approved these changes

2021-05-22 12:28 UTC, Naktakala requested changes
This is ready. It just needs a rebase on the latest development because there were changes to SetKSource

2021-05-24 00:32 UTC, Naktakala approved these changes

2021-05-24 00:32 UTC, merged

2021-05-25 02:15 UTC, ragusa commented on ChiModules/LinearBoltzmannSolver/Tools/kspmonitor_npt.cc
> +  const double SIXTY_SECOND_INTERVAL = 60000.0; //time in milliseconds
how do we know the time was given in msec? 
also, isn't a sixty-second interval also a minute?  If so, why not call this factor: convert_to_minutes or something like that?