Added fissile cross section checks.
chi-tech/chi-tech pull request #187
Opened 2021-07-27 03:43 UTC by zachhardy

### Highlights

- This PR is meant to resolve #146 
- Added various checks to ensure fission related cross sections are appropriate for the application.
- Enforce that `nu`/`chi`, `nu_prompt`/`chi_prompt`, or both are provided in all problems with fission.
- Enforce that `precursor_lambda`, `precursor_yield`, `nu_delayed`, and `chi_delayed` are provided if `num_precursors` is non-zero
-  Enforce unit `precursor_yield` and all `chi` spectra.
- If prompt and delayed quantities are provided, automatically compute `nu = nu_prompt + nu_delayed` and `chi` from `nu`- and `precursor_yield`-weighted prompt and delayed spectra.

2021-08-07 17:23 UTC, dominiccaron requested changes

2021-08-07 17:23 UTC, dominiccaron commented on ChiModules/LinearBoltzmannSolver/lbs_01b_initmaterials.cc
> +              material_xs[matid_to_xs_map[mat_id]]);
This cast is unnecessary.

2021-08-07 17:23 UTC, dominiccaron commented on ChiModules/LinearBoltzmannSolver/lbs_01b_initmaterials.cc
> +              << "the nu/chi prompt values.";
Please add a comment indicating where this assignment will occur (or has already occurred); otherwise, update the text of the warning message. To read a message stating explicitly that an assignment is being made and then not to know if or where the assignment occurs becomes troublesome when trying to trace the events of the code. Perhaps this check is better located where the assignment occurs?

2021-08-07 17:23 UTC, dominiccaron commented on ChiTech/ChiPhysics/PhysicsMaterial/transportxsections/prop_transportxs_01b_readfromchi.cc
> +double eps = std::numeric_limits<float>::epsilon();
Is it intentional to use the single precision machine epsilon in the verifications being made below? If that was your intention, then I recommend to write explicitly `double eps = 1.0e-07;` or similar. The present line is valid C++ thanks to implicit conversion, but might be misinterpreted by the reader as an unintended mistake.

2021-08-09 17:36 UTC, zachhardy commented on ChiModules/LinearBoltzmannSolver/lbs_01b_initmaterials.cc
> +              << "the nu/chi prompt values.";
This was a redundant check. In the cross section parsing process, we check that total or prompt quantities are provided if `sigma_f` has non-zero values, i.e., `is_fissile == true`. This block was removed.

2021-08-09 17:38 UTC, zachhardy commented on ChiModules/LinearBoltzmannSolver/lbs_01b_initmaterials.cc
> +              material_xs[matid_to_xs_map[mat_id]]);
This is true, and I'm also not sure why it was like this. Either way, this block of code has now been removed.

2021-08-09 17:38 UTC, zachhardy commented on ChiTech/ChiPhysics/PhysicsMaterial/transportxsections/prop_transportxs_01b_readfromchi.cc
> +double eps = std::numeric_limits<float>::epsilon();
Modified to `double eps = 1.0e-8;`

2021-08-09 17:55 UTC, Naktakala approved these changes

2021-08-10 18:59 UTC, dominiccaron approved these changes

2021-08-15 19:18 UTC, merged