New mesh syntax in lua input files
chi-tech/chi-tech pull request #376
Opened 2023-09-20 21:10 UTC by ragusa

2023-09-20 23:19 UTC, zachhardy approved these changes
This looks very tedious... Please see the requested changes in the configure dependencies script.

2023-09-20 23:19 UTC, zachhardy commented on resources/configure_dependencies.py
> +        command = f"make OMAKE_PRINTDIR=gmake all -j{argv.jobs}"
```suggestion
         make_command = "make"
         s, e, outstr = ExecSub(make_command + " --version")
         if outstr.find("GNU Make") > 0:
             make_command = "make OMAKE_PRINTDIR=gmake"
             
        command = f"{make_command} all -j{argv.jobs}"
```
Per @Naktakala  suggestion in Slack

2023-09-20 23:19 UTC, zachhardy commented on resources/configure_dependencies.py
> +        command = "make OMAKE_PRINTDIR=gmake install"
```suggestion
        command = "make install"
```
The fix is only needed for `make all`. If you had trouble without it here as well, feel free to disregard. I have never used this here and have never had trouble

2023-09-20 23:19 UTC, zachhardy commented on test/modules/LinearBoltzmannSolvers/DSA/acceleration_diffusion_CFEM.lua
> +-- meshgen1 = chi_mesh.OrthogonalMeshGenerator.Create({ node_sets = {nodes,nodes,znodes} })
Remove, if unused

2023-09-20 23:19 UTC, zachhardy commented on test/modules/LinearBoltzmannSolvers/DSA/acceleration_diffusion_CFEM.lua
>  end
Remove, if unused

2023-09-20 23:19 UTC, zachhardy commented on test/modules/LinearBoltzmannSolvers/DSA/acceleration_diffusion_DFEM.lua
>  end
Remove, if unused

2023-09-20 23:19 UTC, zachhardy commented on test/modules/LinearBoltzmannSolvers/DSA/acceleration_diffusion_DFEM.lua
> +-- meshgen1 = chi_mesh.OrthogonalMeshGenerator.Create({ node_sets = {nodes,nodes,znodes} })
Remove, if unused

2023-09-21 01:01 UTC, ragusa commented on resources/configure_dependencies.py
> +        command = "make OMAKE_PRINTDIR=gmake install"
I followed your suggestion. Then I did a ./configure clean and ./configure. Then re-compile and passed all tests. If this is good enough, then we can go with your suggestion. I think I did a replace-all, that's why line 475 was changed as well.

2023-09-21 16:14 UTC, Naktakala commented on resources/configure_dependencies.py
> +        command = "make OMAKE_PRINTDIR=gmake install"
Just an FYI. The configure.sh only operates on the chi_build directory. Does nothing to dependencies. To really test it you should clean out your dependencies directory and use resources/configure_dependencies.py again.

2023-09-21 16:21 UTC, Naktakala requested changes
This was VERY valuable. If we just remove the configure_dependencies.sh changes then this can move forward. I will fix up configure_dependencies.sh by this afternoon.

2023-09-21 16:21 UTC, Naktakala commented on resources/configure_dependencies.py
> +        s, e, outstr = ExecSub(make_command + " --version")
This crashes. I know you based it on something I pasted in Slack but that copy paste was from code that had other changes.
Solution: Can we remove changes to this file from the PR? Included it in a different scope. I have the fix ready.

2023-09-21 16:22 UTC, Naktakala commented on resources/configure_dependencies.py
> +        s, e, outstr = ExecSub(make_command + " --version")
```
Traceback (most recent call last):
  File "/Users/vermjc/Repos/ChiTech/chi-tech/resources/configure_dependencies.py", line 600, in <module>
    success = InstallPETSC(pkg, ver, gold_file="include/petsc")
  File "/Users/vermjc/Repos/ChiTech/chi-tech/resources/configure_dependencies.py", line 469, in InstallPETSC
    s, e, outstr = ExecSub(make_command + " --version")
ValueError: not enough values to unpack (expected 3, got 2)
```

2023-09-21 18:11 UTC, zachhardy commented on resources/configure_dependencies.py
> +        s, e, outstr = ExecSub(make_command + " --version")
Oops. Let's move it to its own PR.

2023-09-21 21:48 UTC, Naktakala approved these changes

2023-09-21 21:48 UTC, merged